- hosts: 192.468.56.102
  become: yes
  become_user: root
  tasks:
    - name: Install psycopg2 on rebond
      pip:
        name: psycopg2
        executable: pip3

- hosts: 192.468.56.102
  become: yes
  become_user: root
  tasks:
    - name: Check if the database is initialized
      stat:
        path: /var/lib/pgsql/data/pg_hba.conf
      register: stat_result
    - name: Initialize the database
      command: postgresql-setup initdb
      become: yes
      become_user: postgres
      when: not stat_result.stat.exists
    - name: Start postgresql database server and enable the service
      service:
        name: postgresql
        state: started
        enabled: yes 
    - name: Ajust the config file (make the database reachable from the local network)
      postgresql_pg_hba:
        dest: /var/lib/pgsql/data/pg_hba.conf
        contype: host
        users: all
        source: 192.168.56.100/24
        databases: all
        method: md5
    - name: Restart the database server
      service:
        name: postgresql
        state: restarted
    - name: Create the applicative database
      postgresql_db:
        name: appdb
        encoding: UTF-8
      become: yes
      become_user: postgres
    - name: Create applicative user on the database and insure access to the database
      postgresql_user:
        db: appdb
        name: appuser
        password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63646138316232326564633933316633636361383732366266383264633264633831346134626264
          3537336532353737373361646261323262646266633230370a663735633934643439336338613635
          36333133313236643666366565663563363963356630623965613665616432333362666335336366
          6366613835363531320a343039656433326465646439626164343036323531353362396134306431
          3131
        priv: ALL
        state: present
      become: yes
      become_user: postgres
    - name: Ensure user does not have unnecessary privileges
      become_user: postgres
      postgresql_user: 
        name: appuser
        role_attr_flags: NOSUPERUSER,NOCREATEDB
        state: present
