---
- hosts: 192.168.56.102 
  become: yes
  become_user: root
  tasks:
  - name: Install packages
    dnf:
      name: 
        - python3-pip
        - python3-devel
        - gcc
        - postgresql-server
        - postgresql-devel
        - postgresql-contrib
      state: latest
