---
- hosts: 192.168.56.104
  become: yes
  become_user: root
  tasks:
  - name: Add erlang repo
    copy:
      src: files/rabbitmq_erlang.repo
      dest: /etc/yum.repos.d/rabbitmq-erlang.repo
      owner: root
      group: root
      mode: '0644'
  
  - name: Update 
    yum:
      name: '*'
      state: latest
      update_cache: yes
  
  - name: Install erlang
    yum: 
      name: erlang
      state: present
  
  - name: Import rabbitmq signing key 
    rpm_key:
      state: present
      key: https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc
      
  - name: Add rabbit-mq repo
    copy:
      src: files/rabbitmq.repo
      dest: /etc/yum.repos.d/rabbitmq-server.repo
      owner: root
      group: root
      mode: '0644'

  - name: Install rabbitmq-server
    yum: 
      name: rabbitmq-server
      state: present
  
  - name: Enable and start rabbitmq-server service
    service:
      name: rabbitmq-server
      state: started 
      enabled: yes 

  - name: Enables the rabbitmq_management plugin
    rabbitmq_plugin:
      names: rabbitmq_management
      state: enabled

  - name: Open rabbitmq management port 
    firewalld:
      port: 15672/tcp
      permanent: yes
      state: enabled
      immediate: yes 

  - name: Add RabbitMQ admin user 
    rabbitmq_user:
      user: admin
      password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63663930346536323439656565336630323666336633613662333366363730396438623263336466
          6665323639363533633332373632393265666231643862630a626161393530636530633833613232
          35343131303335626363343739633261376536653632393163383235633766346430373436393830
          3534656264346463630a336138616665303635346336653161323931643565386431346566313161
          3664
      vhost: /
      tags: administrator
      configure_priv: .*
      read_priv: .*
      write_priv: .*
      state: present