---
- hosts: 192.168.56.105
  become: yes
  become_user: root
  tasks:
    - name: Install dnf and epel-release
      yum:
        name: "{{packages}}"
        state: present
      vars: 
        packages:
        - dnf
        - epel-release
    - name: Install python3, apache and supervisor
      dnf:
        name: 
          - python3
          - httpd
          - supervisor
          - python3-pip
          - python3-devel
          - python3-virtualenv
        state: latest
    - name: Install virtualenv
      pip:
        name: virtualenv
        executable: pip3
        state: present
    - name: Prepare project directory
      file:
        state: directory 
        mode: '750'
        path: /web
        owner: appli
    - name: remove existing virtualenv
      file:
        path: /web/env
        state: absent
    - name: Create the virtualenv
      pip:
        name: pip
        virtualenv: /web/env
        virtualenv_python: python3
        virtualenv_command: virtualenv-3
    - name: Start and enable httpd
      service:
        name: httpd
        state: started
        enabled: yes
    - name: Open http port 
      firewalld:
        port: 80/tcp
        permanent: yes
        state: enabled
        immediate: yes